package com.auditFal.forms;

import java.sql.Connection;
import java.util.ArrayList;

import com.auditFal.beans.EntitledCompany;
import com.auditFal.beans.Pair;
import com.auditFal.dao.DAOException;
import com.auditFal.dao.DAOUtils;
import com.auditFal.dao.EntitledCompanyDAO;

public class EntitledCompanyForm {
    private EntitledCompanyDAO entitledCompanyDAO;
    private Connection connection;

    public EntitledCompanyForm(Connection connection, EntitledCompanyDAO entitledCompanyDAO) throws Exception {
	this.entitledCompanyDAO = entitledCompanyDAO;
	this.connection = connection;
	this.connection.setAutoCommit(false);
    }

    public ArrayList<Pair<Long>> saveEntitledCompanies(ArrayList<EntitledCompany> entitledCompanies) throws Exception {
	ArrayList<Pair<Long>> autoGeneratedIds = new ArrayList<>();

	try {
	    for (EntitledCompany entitledCompany : entitledCompanies) {
		// Check if item already exists on DB
		EntitledCompany check = entitledCompanyDAO.find(connection, entitledCompany);
		// if it does
		if (check != null) {
		    if (check.getId().longValue() != entitledCompany.getId().longValue())
			;
		    {
			Pair<Long> pair = new Pair<>();
			/* oldId */ pair.value1 = entitledCompany.getId();
			/* id */ pair.value2 = check.getId();
			entitledCompany.setId(check.getId());
			autoGeneratedIds.add(pair);
		    }
		    // Update the item
		    entitledCompanyDAO.update(connection, entitledCompany);

		    // ...otherwise insert a new element
		} else {
		    Pair<Long> pair = new Pair<>();
		    /* oldId */ pair.value1 = entitledCompany.getId();
		    /* id */ pair.value2 = entitledCompanyDAO.create(connection, entitledCompany);
		    autoGeneratedIds.add(pair);
		}
	    }

	    connection.commit();

	} catch (DAOException e) {
	    connection.rollback();
	    System.out.println(e.getMessage());
	    throw new Exception(e);
	} finally {
	    DAOUtils.closeConnection(connection);
	}

	return autoGeneratedIds;
    }

    public ArrayList<EntitledCompany> getEntitledCompanies() throws Exception {

	try {
	    return entitledCompanyDAO.getAll(connection);

	} catch (DAOException e) {
	    System.out.println(e.getMessage());
	    throw new Exception(e);
	} finally {
	    DAOUtils.closeConnection(connection);
	}
    }
}
