package com.auditFal.forms;

import java.sql.Connection;
import java.util.ArrayList;

import com.auditFal.beans.EntitledCompany;
import com.auditFal.beans.Pair;
import com.auditFal.dao.DAOException;
import com.auditFal.dao.DAOUtils;
import com.auditFal.dao.EntitledCompanyDAO;

public class EntitledCompanyForm {
	private EntitledCompanyDAO entitledCompanyDAO;
	private Connection connection;
	
	public EntitledCompanyForm(Connection connection, EntitledCompanyDAO entitledCompanyDAO) throws Exception {
		this.entitledCompanyDAO = entitledCompanyDAO;
		this.connection = connection;
		this.connection.setAutoCommit(false);
	}
	
	public ArrayList<Pair<Long>> saveWorkStations(ArrayList<EntitledCompany> entitledCompanies) throws Exception {
		ArrayList<Pair<Long>> autoGeneratedIds = new ArrayList<Pair<Long>>();
		
		try {
			for(EntitledCompany entitledCompany : entitledCompanies) {
				// Check if item already exists on DB
				EntitledCompany check = this.entitledCompanyDAO.find(connection, entitledCompany);
				// if it does
				if(check != null) {
					if(check.getId().longValue() != entitledCompany.getId().longValue()); {
						Pair<Long> pair = new Pair<>();
						/* oldId */	pair.value1 = entitledCompany.getId();
						/* id */	pair.value2 = check.getId();
						entitledCompany.setId(check.getId());
						autoGeneratedIds.add(pair);
					}
					//Update the item
					this.entitledCompanyDAO.update(this.connection, entitledCompany);
					
					//...otherwise insert a new element
				} else {
					Pair<Long> pair = new Pair<>();
					/* oldId */	pair.value1 = entitledCompany.getId();
					/* id */	pair.value2 = this.entitledCompanyDAO.create(this.connection, entitledCompany);
					autoGeneratedIds.add(pair);	
				}
			}
			
			this.connection.commit();
			
		} catch (DAOException e) {
			this.connection.rollback();
			System.out.println(e.getMessage());
			throw new Exception(e);
		} finally {
			DAOUtils.closeConnection(this.connection);
		}		
		
		return autoGeneratedIds;
	}
}
