package com.auditFal.forms;

import java.sql.Connection;
import java.util.ArrayList;

import com.auditFal.beans.Pair;
import com.auditFal.beans.Post;
import com.auditFal.dao.DAOException;
import com.auditFal.dao.DAOFactory;
import com.auditFal.dao.DAOUtils;
import com.auditFal.dao.PostDAO;

public class PostForm {

    private PostDAO postDAO;
    private Connection connection;

    public PostForm(DAOFactory daoFactory) throws Exception {
	postDAO = daoFactory.getPostDAO();
	connection = daoFactory.getConnection();
	connection.setAutoCommit(false);
    }

    public ArrayList<Pair<Long>> savePosts(ArrayList<Post> posts) throws Exception {
	ArrayList<Pair<Long>> autoGeneratedIds = new ArrayList<>();

	try {
	    for (Post post : posts) {
		// Check if item already exists on DB
		Post check = postDAO.find(connection, post);
		// if it does
		if (check != null) {
		    if (check.getId().longValue() != post.getId().longValue())
			;
		    {
			Pair<Long> pair = new Pair<>();
			/* oldId */ pair.value1 = post.getId();
			/* id */ pair.value2 = check.getId();
			post.setId(check.getId());
			autoGeneratedIds.add(pair);
		    }
		    // Update the item
		    postDAO.update(connection, post);

		    // ...otherwise insert a new element
		} else {
		    Pair<Long> pair = new Pair<>();
		    /* oldId */ pair.value1 = post.getId();
		    /* id */ pair.value2 = postDAO.create(connection, post);
		    autoGeneratedIds.add(pair);
		}
	    }

	    connection.commit();

	} catch (DAOException e) {
	    connection.rollback();
	    System.out.println(e.getMessage());
	    throw new Exception(e);
	} finally {
	    DAOUtils.closeConnection(connection);
	}

	return autoGeneratedIds;
    }

    public ArrayList<Post> getPosts() throws Exception {

	try {
	    return postDAO.getAll(connection);

	} catch (DAOException e) {
	    System.out.println(e.getMessage());
	    throw new Exception(e);
	} finally {
	    DAOUtils.closeConnection(connection);
	}
    }
}
