package com.auditFal.forms;

import java.sql.Connection;
import java.util.ArrayList;

import com.auditFal.beans.Pair;
import com.auditFal.beans.WorkStation;
import com.auditFal.dao.DAOException;
import com.auditFal.dao.DAOUtils;
import com.auditFal.dao.WorkStationDAO;

public class WorkStationForm {
	
	private WorkStationDAO workStationDAO;
	private Connection connection;
	
	public WorkStationForm(Connection connection, WorkStationDAO workStationDAO) throws Exception {
		this.workStationDAO = workStationDAO;
		this.connection = connection;
		this.connection.setAutoCommit(false);
	}
	
	public ArrayList<Pair<Long>> saveWorkStations(ArrayList<WorkStation> workStations) throws Exception {
		ArrayList<Pair<Long>> autoGeneratedIds = new ArrayList<Pair<Long>>();
		
		try {
			for(WorkStation workSation : workStations) {
				// Check if item already exists on DB
				WorkStation check = this.workStationDAO.find(connection, workSation);
				// if it does
				if(check != null) {
					if(check.getId().longValue() != workSation.getId().longValue()); {
						Pair<Long> pair = new Pair<>();
						/* oldId */	pair.value1 = workSation.getId();
						/* id */	pair.value2 = check.getId();
						workSation.setId(check.getId());
						autoGeneratedIds.add(pair);
					}
					//Update the item
					this.workStationDAO.update(this.connection, workSation);
					
					//...otherwise insert a new element
				} else {
					Pair<Long> pair = new Pair<>();
					/* oldId */	pair.value1 = workSation.getId();
					/* id */	pair.value2 = this.workStationDAO.create(this.connection, workSation);
					autoGeneratedIds.add(pair);	
				}
			}
			
			this.connection.commit();
			
		} catch (DAOException e) {
			this.connection.rollback();
			System.out.println(e.getMessage());
			throw new Exception(e);
		} finally {
			DAOUtils.closeConnection(this.connection);
		}		
		
		return autoGeneratedIds;
	}
	
public ArrayList<WorkStation> getWorkStations() throws Exception {		
		
		try {
			return this.workStationDAO.getAll(this.connection);
			
		} catch (DAOException e) {
			System.out.println(e.getMessage());
			throw new Exception(e);
		} finally {
			DAOUtils.closeConnection(this.connection);
		}		
	}
}
