package com.auditFal.forms;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;

import com.auditFal.beans.Pair;
import com.auditFal.beans.WorkStation;
import com.auditFal.dao.DAOException;
import com.auditFal.dao.DAOUtils;
import com.auditFal.dao.WorkStationDAO;

public class WorkStationForm {
	
	private WorkStationDAO workStationDAO;
	private Connection connection;
	
	public WorkStationForm(Connection connection, WorkStationDAO workStationDAO) throws Exception {
		this.workStationDAO = workStationDAO;
		this.connection = connection;
		this.connection.setAutoCommit(false);

	}
	
	public ArrayList<Pair<Long>> saveWorkStations(ArrayList<WorkStation> workStations) throws Exception {
		ArrayList<Pair<Long>> autoGeneratedIds = new ArrayList<Pair<Long>>();
		
		try {
			for(WorkStation workSation : workStations) {
				Pair<Long> pair = new Pair<>();
				/* oldId */	pair.value1 = workSation.getId();
				/* id */	pair.value2 = this.workStationDAO.create(this.connection, workSation);
				autoGeneratedIds.add(pair);
			}
			
			this.connection.commit();
			
		} catch (DAOException e) {
			this.connection.rollback();
			System.out.println(e.getMessage());
			throw new Exception(e);
		} finally {
			DAOUtils.closeConnection(this.connection);
		}		
		
		return autoGeneratedIds;
	}
}
