package com.auditFal.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import com.auditFal.beans.Building;

public class PostgresBuildingDAO extends BuildingDAO {

    // @formatter:off
    private static final String SQL_CREATE 				= "INSERT INTO buildings (name, lowerName, active) VALUES (?, ?, ?)";
    private static final String SQL_FIND_BY_LOWER_NAME 			= "SELECT * FROM buildings WHERE lowername = ?";
    private static final String SQL_UPDATE 				= "UPDATE buildings SET name = ?, lowerName = ?, active = ? WHERE id = ?";
    private static final String SQL_FIND_BY_ID 				= "SELECT * FROM buildings WHERE id = ?";
    private static final String SQL_BUILDINGS_WORKSTATIONS_DELETE 	= "DELETE FROM buildings_workstations WHERE id_buildings = ? AND id_workstations = ?";
    private static final String SQL_BUILDINGS_WORKSTATIONS_CREATE 	= "INSERT INTO buildings_workstations (id_buildings, id_workstations) VALUES (?, ?)";
    private static final String SQL_BUILDINGS_WORKSTATIONS_FIND 	= "SELECT * FROM buildings_workstations WHERE id_buildings = ?";
    private static final String SQL_GET_ALL 				= "SELECT * FROM buildings";
    // @formatter:on

    @Override
    public Long create(Connection connection, Building building) throws DAOException {
	PreparedStatement preparedStatement = null;
	ResultSet autoGeneratedKey = null;

	try {
	    String name = building.getName();
	    String lowerName = building.getLowerName();
	    Boolean active = building.getActive();

	    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_CREATE, true, name, lowerName, active);
	    int sqlStatus = preparedStatement.executeUpdate();

	    if (sqlStatus == 0)
		throw new DAOException("Échec de la création de l'item, aucune ligne ajoutée dans la table.");

	    /* Retrieve the autoGenerated key after insertion */
	    autoGeneratedKey = preparedStatement.getGeneratedKeys();
	    if (autoGeneratedKey.next()) {
		Long itemId = autoGeneratedKey.getLong(1);

		syncDependencies(connection, itemId, building.getDependencies());

		return itemId;
	    } else
		throw new DAOException("Échec de la création de l'utilisateur en base, aucun ID auto-généré retourné.");
	} catch (SQLException e) {
	    throw new DAOException(e);
	} finally {
	    DAOUtils.closeResultSet(autoGeneratedKey);
	    DAOUtils.closeStatement(preparedStatement);
	}
    }

    @Override
    public Building find(Connection connection, Building building) throws DAOException {
	return findByLowerName(connection, building.getLowerName());
    }

    @Override
    public Building findById(Connection connection, Long id) throws DAOException {
	PreparedStatement preparedStatement = null;
	ResultSet result = null;

	try {
	    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_FIND_BY_ID, false, id);
	    result = preparedStatement.executeQuery();
	    if (result.next())
		return Building.parseResultSet(result);
	    else
		return null;
	} catch (SQLException e) {
	    throw new DAOException(e);
	} finally {
	    DAOUtils.closeResultSet(result);
	    DAOUtils.closeStatement(preparedStatement);
	}
    }

    @Override
    public Building findByLowerName(Connection connection, String lowerName) throws DAOException {
	PreparedStatement preparedStatement = null;
	ResultSet result = null;

	try {
	    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_FIND_BY_LOWER_NAME, false, lowerName);
	    result = preparedStatement.executeQuery();
	    if (result.next())
		return Building.parseResultSet(result);
	    else
		return null;
	} catch (SQLException e) {
	    throw new DAOException(e);
	} finally {
	    DAOUtils.closeResultSet(result);
	    DAOUtils.closeStatement(preparedStatement);
	}
    }

    @Override
    public void update(Connection connection, Building building) throws DAOException {
	PreparedStatement preparedStatement = null;
	try {
	    Long id = building.getId();
	    String name = building.getName();
	    String lowerName = building.getLowerName();
	    Boolean active = building.getActive();
	    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_UPDATE, false, name, lowerName, active,
		    id);
	    int sqlStatus = preparedStatement.executeUpdate();

	    if (sqlStatus == 0)
		throw new DAOException("Échec de la mise à jour de l'item, aucune ligne modifiée dans la table.");

	    syncDependencies(connection, id, building.getDependencies());

	} catch (Exception e) {
	    throw new DAOException(e);
	} finally {
	    DAOUtils.closeStatement(preparedStatement);
	}
    }

    private void syncDependencies(Connection connection, Long itemId, ArrayList<Long> dependencies)
	    throws SQLException {
	PreparedStatement preparedStatement = null;
	ResultSet result = null;

	try {
	    // get all junctions
	    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_BUILDINGS_WORKSTATIONS_FIND, false,
		    itemId);
	    result = preparedStatement.executeQuery();
	    ArrayList<Long> junctionsToRemove = new ArrayList<>();
	    ArrayList<Long> junctionsToKeep = new ArrayList<>();

	    while (result.next()) {
		Long id = result.getLong("id_workstations");
		if (dependencies.contains(id))
		    junctionsToKeep.add(id);
		else
		    junctionsToRemove.add(id);
	    }
	    // Remove junctions
	    for (Long buildingId : junctionsToRemove) {
		DAOUtils.closeStatement(preparedStatement);
		preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_BUILDINGS_WORKSTATIONS_DELETE, false,
			itemId, buildingId);
		preparedStatement.executeUpdate();
	    }

	    // Add junctions
	    for (long id : dependencies)
		if (!junctionsToKeep.contains(id)) {
		    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_BUILDINGS_WORKSTATIONS_CREATE,
			    false, itemId, id);
		    preparedStatement.executeUpdate();
		}

	} catch (SQLException e) {
	    throw new DAOException(e);
	} finally {
	    DAOUtils.closeResultSet(result);
	    DAOUtils.closeStatement(preparedStatement);
	}

    }

    @Override
    public ArrayList<Building> getAll(Connection connection) throws DAOException {
	PreparedStatement preparedStatement = null;
	ResultSet result = null;
	ArrayList<Building> buildings = new ArrayList<>();

	try {
	    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_GET_ALL, false);
	    result = preparedStatement.executeQuery();

	    while (result.next())
		buildings.add(Building.parseResultSet(result));

	    // Get all dependencies for each buildings
	    for (Building building : buildings)
		building.setDependencies(getDependencies(connection, building.getId()));

	    return buildings;
	} catch (SQLException e) {
	    throw new DAOException(e);
	} finally {
	    DAOUtils.closeResultSet(result);
	    DAOUtils.closeStatement(preparedStatement);
	}
    }

    private ArrayList<Long> getDependencies(Connection connection, Long itemId) throws SQLException {
	PreparedStatement preparedStatement = null;
	ResultSet result = null;
	ArrayList<Long> dependencies = new ArrayList<>();

	try {
	    preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_BUILDINGS_WORKSTATIONS_FIND, false,
		    itemId);
	    result = preparedStatement.executeQuery();

	    while (result.next())
		dependencies.add(result.getLong("id_workstations"));

	    return dependencies;
	} catch (SQLException e) {
	    throw new DAOException(e);
	} finally {
	    DAOUtils.closeResultSet(result);
	    DAOUtils.closeStatement(preparedStatement);
	}
    }

}
