package com.auditFal.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.auditFal.beans.WorkStation;

public class PostgresWorkStationDAO extends WorkStationDAO {
	
	private static final String SQL_CREATE = "INSERT INTO workstations (name, lowerName, active) VALUES (?, ?, ?)";

	@Override
	public Long create(Connection connection, WorkStation workStation) throws DAOException {
		PreparedStatement preparedStatement = null;
		ResultSet autoGeneratedKey = null;
		
		try {
			String name = workStation.getName();
			String lowerName = workStation.getLowerName();
			Boolean active = workStation.getActive();
			
			preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_CREATE, true, name, lowerName, active);
			int sqlStatus = preparedStatement.executeUpdate();
			
			if ( sqlStatus == 0 )
	            throw new DAOException( "Échec de la création de l'utilisateur, aucune ligne ajoutée dans la table." );
			
	        /* Retrieve the autoGenerated key after insertion */
			autoGeneratedKey = preparedStatement.getGeneratedKeys();
	        if ( autoGeneratedKey.next() ) {
	        	return autoGeneratedKey.getLong( 1 );
	        } else {
	            throw new DAOException( "Échec de la création de l'utilisateur en base, aucun ID auto-généré retourné." );
	        }
		} catch (SQLException e) {
			throw new DAOException(e);
		}finally {
			DAOUtils.closeResultSet(autoGeneratedKey);
			DAOUtils.closeStatement(preparedStatement);
		}
	}

	@Override
	public WorkStation findById(Connection connection, Long id) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

}
