package com.auditFal.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.auditFal.beans.WorkStation;

public class PostgresWorkStationDAO extends WorkStationDAO {
	
	private static final String SQL_CREATE = "INSERT INTO workstations (name, active) VALUES (?, true)";

	@Override
	public Long create(Connection connection, WorkStation workStation) throws DAOException {
		PreparedStatement preparedStatement = null;
		ResultSet autoGeneratedKey = null;
		
		try {
			preparedStatement = DAOUtils.initPreparedStatement(connection, SQL_CREATE, true, workStation.getName());
			int sqlStatus = preparedStatement.executeUpdate();
			if ( sqlStatus == 0 ) {
	            throw new DAOException( "Échec de la création de l'utilisateur, aucune ligne ajoutée dans la table." );
	        }
	        /* Retrieve the autoGenerated key after insertion */
			autoGeneratedKey = preparedStatement.getGeneratedKeys();
	        if ( autoGeneratedKey.next() ) {
	        	return autoGeneratedKey.getLong( 1 );
	        } else {
	            throw new DAOException( "Échec de la création de l'utilisateur en base, aucun ID auto-généré retourné." );
	        }
		} catch (SQLException e) {
			throw new DAOException(e);
		}finally {
			DAOUtils.closeResultSet(autoGeneratedKey);
			DAOUtils.closeStatement(preparedStatement);
		}
	}

	@Override
	public WorkStation findById(Connection connection, Long id) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

}
