package com.auditFal.controlers;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Iterator;

import javax.servlet.http.HttpServletResponse;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import com.auditFal.beans.Pair;
import com.auditFal.beans.WorkStation;
import com.auditFal.dao.DAOFactory;
import com.auditFal.forms.WorkStationForm;

public class SaveWorkstationsControler {
    @SuppressWarnings("unchecked")
    public static String saveWorkstations(String body, HttpServletResponse resp, DAOFactory daoFactory) {

	ArrayList<WorkStation> workStations = new ArrayList<>();
	resp.setContentType("application/json; charset=utf-8");

	try {
	    PrintWriter writer = resp.getWriter();
	    JSONArray requestBody = new JSONArray();
	    JSONParser jsonParser = new JSONParser();
	    requestBody = (JSONArray) jsonParser.parse(body);

	    Iterator<JSONObject> iterator = requestBody.iterator();
	    while (iterator.hasNext())
		workStations.add(WorkStation.parse(iterator.next()));

	    WorkStationForm workStationForm = new WorkStationForm(daoFactory);
	    ArrayList<Pair<Long>> autoGeneratedIds = workStationForm.saveWorkStations(workStations);

	    /*
	     * construct the response body (format : [{"oldId":-1, "id":1},{"oldId":-2,
	     * "id":2},...])
	     */
	    JSONArray jsonResp = new JSONArray();

	    for (Pair<Long> line : autoGeneratedIds) {
		JSONObject jsonPair = new JSONObject();
		jsonPair.put("oldId", line.value1);
		jsonPair.put("id", line.value2);
		jsonResp.add(jsonPair);
	    }

	    /* write the response into the response body */
	    writer.print(jsonResp.toJSONString());

	    return jsonResp.toJSONString();

	} catch (Exception e) {
	    e.printStackTrace();
	    resp.setStatus(500);
	    return "";
	}
    }
}
